name: Run media_upload_v2.py every 8 hours

on:
  workflow_dispatch:
  schedule:
    # 使用 Cron 表达式设置每 8 小时运行一次
    - cron: "1 */8 * * *"  # 每 8 小时运行一次

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 检出代码库
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # 使用 Python 3.x

      # 安装 Python 依赖
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pynacl requests python-dotenv requests-oauthlib cryptography

      # 运行 Python 脚本
      - name: Run media_upload_v2.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          python media_upload_v2.py
      
      # 自动添加和提交更改
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.' # 添加所有更改
          message: "Automated changes by GitHub Actions" # 提交信息
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的默认 token